apiVersion: v1
kind: Service
metadata:
  name: magic-resume
  namespace: magic-resume
spec:
  type: ClusterIP
  selector:
    app: magic-resume
  ports:
    - name: http
      port: 80
      targetPort: http
